feat: do not store properties decorated with @Ignore() decorator
wovalle/fireorm pull request #249
Opened 2021-04-24 06:02 UTC by danieleisenhardt

New decorator allows for entities to have properties that are not stored.

2021-05-11 21:21 UTC, wovalle requested changes
Great use of the Reflection api and great work! just a minor comment.

2021-05-11 21:21 UTC, wovalle commented on src/utils.ts
> +
Can you create some tests for this case? After serialization, the "ignored" properties shouldn't be serialized

2021-05-11 21:22 UTC, wovalle commented
Still missing (will probably create an issue for this):

- One integration test
- Documentation

2021-05-12 11:12 UTC, danieleisenhardt commented
> * One integration test
> * Documentation

I'll do my best to add these to the branch.

2021-05-13 15:56 UTC, wovalle approved these changes

2021-05-13 15:56 UTC, wovalle commented
Great work! @danieleisenhardt

2021-05-13 15:56 UTC, merged

2021-05-13 15:57 UTC, wovalle commented
@all-contributors add @danieleisenhardt for code